apiVersion: apps/v1
kind: Deployment
metadata:
  
  name: mysql8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql8
 
  template:
    metadata:
     
      labels:
        app: mysql8
    spec:
      containers:
      - image: mysql:8
        name: mysql
        ports:
        - containerPort: 3307
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mateo
        - name: MYSQL_DATABASE
          value: sisdb2025

status: {}