version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: some-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sisdb2025
      MYSQL_USER: root
      MYSQL_PASSWORD: mateo
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  spring:
    image: spring
    container_name: springboot_sisdb2025
    depends_on:
      - mysql
    ports:
      - "8002:8002"
    networks:
      - app_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/sisdb2025
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data:

networks:
  app_network:
